command_chaining = true
enter_accept = false
keymap_mode = "auto"
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-bar", vim_normal = "steady-block" }

[theme]
name = "catppuccin-macchiato"
