command_chaining = true
enter_accept = true
keymap_mode = "vim-normal"
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-bar", vim_normal = "steady-block" }

[theme]
name = "catppuccin-macchiato"
